def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Error: Division by zero is not allowed."
    return x / y

def exponentiate(x, y):
    return x ** y

def modulus(x, y):
    if y == 0:
        return "Error: Modulus by zero is not allowed."
    return x % y

def get_number(prompt):
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("Invalid input. Please enter a numeric value.")

def main():
    print("Welcome to the simple calculator!")

    operations = {
        '+': add,
        '-': subtract,
        '*': multiply,
        '/': divide,
        '**': exponentiate,
        '%': modulus
    }

    while True:
        print("Choose an operation: +, -, *, /, **, % or type 'exit' to quit")
        operation = input().strip()

        if operation == "exit":
            break

        if operation not in operations:
            print("Invalid operation. Please try again.")
            continue

        num1 = get_number("Enter the first number: ")
        num2 = get_number("Enter the second number: ")

        # LBYL approach
        if operation in ['/','%']:
            if num2 == 0:
                print("Error: Division or Modulus by zero is not allowed.")
                continue

        # EAFP approach
        try:
            result = operations[operation](num1, num2)
        except ZeroDivisionError:
            result = "Error: Division by zero is not allowed."
        except Exception as e:
            result = f"Error: {e}"

        print(f"Result: {result}")

    print("Thank you for using the calculator. Goodbye!")

if __name__ == "__main__":
    main()
